#!/bin/bash
# ──────────────────────────────────────────────────────────────────────────────
# Sutherland Global Services — RP Knowledge Graph
# neo4j-admin database import command
# Generated by parquet_to_neo4j_csv.py
#
# BEFORE RUNNING:
#   1. docker stop neo4j_rp
#   2. docker volume rm neo4j_data  (or clear the data folder)
#   3. Run this script
#   4. docker start neo4j_rp
#   5. python schema.py  (creates indexes — constraints already embedded)
# ──────────────────────────────────────────────────────────────────────────────

IMPORT_DIR="/var/lib/neo4j/import"   # path inside container
CONTAINER="neo4j_rp"

docker exec $CONTAINER neo4j-admin database import full neo4j \
  --nodes=Patient=$IMPORT_DIR/nodes_patient.csv \
  --nodes=Practice=$IMPORT_DIR/nodes_practice.csv \
  --nodes=Location=$IMPORT_DIR/nodes_location.csv \
  --nodes=InsurancePlan=$IMPORT_DIR/nodes_insurance.csv \
  --nodes=Campaign=$IMPORT_DIR/nodes_campaign.csv \
  --nodes=BirdeyeReview=$IMPORT_DIR/nodes_birdeye.csv \
  --nodes=Visit=$IMPORT_DIR/nodes_visit.csv \
  --nodes=Charge=$IMPORT_DIR/nodes_charge.csv \
  --nodes=Transaction=$IMPORT_DIR/nodes_transaction.csv \
  --nodes=Statement=$IMPORT_DIR/nodes_statement.csv \
  --nodes=RCCall=$IMPORT_DIR/nodes_rccall.csv \
  --nodes=IVRInbound=$IMPORT_DIR/nodes_ivrinbound.csv \
  --nodes=DiallerCall=$IMPORT_DIR/nodes_diallercall.csv \
  --nodes=PhoneBridge=$IMPORT_DIR/nodes_phonebridge.csv \
  --nodes=DiagnosisCode=$IMPORT_DIR/nodes_diagnosiscode.csv \
  --nodes=ProcedureCode=$IMPORT_DIR/nodes_procedurecode.csv \
  --relationships=REGISTERED_AT=$IMPORT_DIR/rel_patient_practice.csv \
  --relationships=BELONGS_TO_PRACTICE=$IMPORT_DIR/rel_location_practice.csv \
  --relationships=ISSUED_BY_PRACTICE=$IMPORT_DIR/rel_insurance_practice.csv \
  --relationships=RUN_BY=$IMPORT_DIR/rel_campaign_practice.csv \
  --relationships=REVIEWS=$IMPORT_DIR/rel_birdeye_location.csv \
  --relationships=HAD_VISIT=$IMPORT_DIR/rel_patient_visit.csv \
  --relationships=PERFORMED_AT=$IMPORT_DIR/rel_visit_location.csv \
  --relationships=UNDER_PLAN=$IMPORT_DIR/rel_visit_insurance.csv \
  --relationships=HAS_CHARGE=$IMPORT_DIR/rel_patient_charge.csv \
  --relationships=PART_OF_VISIT=$IMPORT_DIR/rel_charge_visit.csv \
  --relationships=AT_LOCATION=$IMPORT_DIR/rel_charge_location.csv \
  --relationships=DIAGNOSED_WITH=$IMPORT_DIR/rel_charge_diagnosis.csv \
  --relationships=USES_PROCEDURE=$IMPORT_DIR/rel_charge_procedure.csv \
  --relationships=SETTLES=$IMPORT_DIR/rel_transaction_charge.csv \
  --relationships=HAS_TRANSACTION=$IMPORT_DIR/rel_patient_transaction.csv \
  --relationships=RECEIVED_STATEMENT=$IMPORT_DIR/rel_patient_statement.csv \
  --relationships=PART_OF_CAMPAIGN=$IMPORT_DIR/rel_rccall_campaign.csv \
  --relationships=ATTRIBUTED_TO_PHONE=$IMPORT_DIR/rel_rccall_phonebridge.csv \
  --relationships=IDENTIFIED_BY_PHONE=$IMPORT_DIR/rel_patient_phonebridge.csv \
  --relationships=CALLED_IVR=$IMPORT_DIR/rel_patient_ivr.csv \
  --relationships=CONTACTED_BY_DIALLER=$IMPORT_DIR/rel_patient_dialler.csv \
  --skip-bad-relationships=true \
  --skip-duplicate-nodes=true \
  --high-io=true \
  --verbose

echo "Import complete. Starting Neo4j..."
docker start $CONTAINER
echo "Done. Run: python schema.py to create indexes."
